export const TreeUiActionTypes = {
    TOGGLE_EXPAND: 'TOGGLE_EXPAND',
    EXPAND_CLOSE_CHILDREN: 'EXPAND_CLOSE_CHILDREN',
    EXPAND_HIEARCHY: 'EXPAND_HIEARCHY',
    EXPAND_ABOVE_LEAFS: 'EXPAND_ABOVE_LEAFS',
    EXPAND_ALL: 'EXPAND_ALL',
    COLLAPSE_ALL: 'COLLAPSE_ALL',
    INIT_STATE: 'INIT_STATE'
  } as const
  